import Head from 'next/head'
import Header from '../src/components/Header'
import Homepage from '../src/components/Homepage'
import Footer from '../src/components/Footer'

export default function Home() {
	return (
		<div>
			<Head>
				<title>SamuelHolmes.tech</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='icons/favicon.ico' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<meta name='theme-color' content='#000000' />
				<meta
					name='SamuelHolmes.tech'
					content='Développeur Full Stack Autodidacte'
				/>
				<link
					rel='apple-touch-icon'
					href='/icons/android-chrome-192x192.png'
				/>

				<link rel='manifest' href='/site.webmanifest' />
			</Head>

			<Header />
			<Homepage />
			<Footer />
		</div>
	)
}
